### ISSUE TITLE
Warning: session_start(): Failed to read session data: user (path:)

### ISSUE THREAD

**Issue by tennom** [dominicklee/PHP-MySQL-Sessions#1]
### I couldn't make this code work with both the latest stable PHP7.2.2 and PHP7.1.X. 
I also had the --enable-fpm with compilations. It showed this error `Warning: session_start(): Failed to read session data: user (path:)`. 
I also tried to override default session manager with `implements \SessionHandlerInterface` which returned same error. Then I started doubting some compatibility issues of 7.2 and 7.1 with `session_set_save_handler`, but can't find any proof and not much time dig in as of now.  
### I could make it work with PHP7.0.X. builds with no problem!

**Comment by wintstar** [comment]
Check this

replace
```
	public function _read($id){
		// Set query
		$this->db->query('SELECT data FROM sessions WHERE id = :id');
		// Bind the Id
		$this->db->bind(':id', $id);
		// Attempt execution
		// If successful
		if($this->db->execute()){
		// Save returned row
		$row = $this->db->single();
		// Return the data
		return $row['data'];
		}else{
		// Return an empty string
		return '';
		}
	}
```
with this
```
	public function _read($id){
		// Set query
		$this->db->query('SELECT data FROM sessions WHERE id = :id');
		// Bind the Id
		$this->db->bind(':id', $id);
		// Attempt execution
		// If successful
		if($this->db->execute()){
			// Save returned row
			$row = $this->db->single();
			// Return the data
			if (is_null($row['data'])) {
				return '';
			}
			return $row['data'];
		}
	}
```
works with php 7.1

**Comment by tennom** [comment]
Thanks for the solution. I learned that php 7.1 and above strictly requires the session read to return a string and not even a null value. That's why the error was raised. This code also raised an error when using registration-ID function. Because it follows a different action cycle in 7.1 and above I suspect, like read->close->read->write...  I will post my code when i return to that problem soon.

**Comment by jtangu** [comment]
Hi I'm having the same issue with migrating from PHP 7.0 to 7.1

I'm trying to find which file has the above stated code to update the function _read. Sorry I'm new.

**Comment by tennom** [comment]
I used a different approach. I don't think wintstar's code solves the issue.

**Comment by jtangu** [comment]
Hi. May you please share with me your solution? I'm finding it terribly
difficult to migrate php 7.0 to 7.1 thanks.

**Comment by arslannawaz** [comment]
> I used a different approach. I don't think wintstar's code solves the issue.

Kindly share your approach here? wintstar's code do not works for me.
