### ISSUE TITLE
PHP7.1 didn't work for me.

### ISSUE THREAD

**Issue by bevhost** [dominicklee/PHP-MySQL-Sessions#2]
https://github.com/dominicklee/PHP-MySQL-Sessions/blob/366699f548a9b7d4847f466b07f497c1d17c8ddd/mysql.sessions.php#L78

This line was returning false on the first call when the session is created.
PHP detected this error and so session did not work.

**Comment by Maniace2** [comment]
Please note that in newer PHP versions you can't return NULL from read function. You have to return empty string instead.

So if you get error
Warning: session_start(): Failed to read session data
change following part of code in _read function
`

		if($this->db->execute()){
			// Save returned row
			$row = $this->db->single();
			// Return the data
			return $row['data'];
		} else {
`
to
`

		if($this->db->execute()){
			// Save returned row
			$row = $this->db->single();
			if (is_null($row['data']))
				return '';
		
			// Return the data
			return $row['data'];
		} else {
`

**Comment by dominicklee** [comment]
@Maniace2 Thank you for fixing the function! I will update the repository with your fixes as needed.
